export const ROUTES = {
  home: "/",
  classes: "/classes",
  schedule: "/schedule",
  teacher: "/teacher",
  pricing: "/pricing",
  admin: "/admin",
  adminClassCards: "/admin/class-cards",
  adminSessions: "/admin/sessions",
  adminPricing: "/admin/pricing",
  adminMembers: "/admin/members",
  adminSubscriptions: "/admin/subscriptions",
  adminBookings: "/admin/bookings",
  adminSubscribers: "/admin/subscribers",
  adminClasses: "/admin/classes",
  sunset: "/#sunset",
  bookApp: "/#book-app",
} as const;
